# Generated by Django 4.1.7 on 2023-02-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_student_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exam_link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
